Add-on Implementation
SemenSofronov/product-tour-add-on pull request #1
Opened 2018-07-31 14:31 UTC by SemenSofronov

2018-08-01 11:57 UTC, glebfox requested changes

2018-08-01 11:57 UTC, glebfox commented on modules/global/src/com/company/scenarioaddon/entity/TestEntity.java
> +public class TestEntity extends StandardEntity {
Аддон не должен включать в себя тестовые сущности и UI

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Tour.java
> +    void addStep(Step step);
Ты пропустил несколько методов

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Tour.java
> +        class ShowEvent extends TourEvent {
Мы так не делаем. Если ты не вынес интерфейс слушателя в отдельный файл, то класть класс события внутрь интерфейса не надо, просто расположи его ниже.
То же относится и к родительскому классу событий тура. Если он живет в своем отдельном файле, то и логично вынести в отдельные файлы интерфейсы слушателей и событий, аналогично оригинальному аддону. Или можно сделать как у CUBA обычно мы делаем, все слушатели и эвенты лежат в интерфейсе компонента.

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Tour.java
> +    interface TourCancelListener {
На самом деле, с приходом Java 8, создавать интерфейсы слушателей с одним единственным методом стало не модно. Вместо этого можно писать так: `void addCancelListener(Consumer<CancelEvent> listener);`

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/TourEvent.java
> +        return null;
А поему тут `null`?

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +import com.haulmont.cuba.gui.components.AbstractAction;
У тебя есть неиспользуемые импорты

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +
Пустые строки

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +        tour = new org.vaadin.addons.producttour.tour.Tour();
Вынеси создание Тура в метод, чтобы код был расширяемым

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +        WebStep webStep = (WebStep) step;
А если я передам собственную релизацию интерфейса `Step`, но не наследующую `WebStep`?

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +        WebStep webStep = (WebStep) step;
Аналогично комменту выше. Посмотри на метод `unwrap` в платформенных компонентах в качестве подсказки, как можно сделать.

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +        return stepMap.get(currentStep);
Жирно иметь такую Map. Я предлагал тебе сделать как в `WebDataGrid.getColumnByGridColumn`.

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +        return stepMap.get(step);
У тебя тут исключение упадет, если `step` окажется `null`. Если `stepId = null`, то нет вообще смысла что либо искать. Если метод может вернуть `null`, то надо поставить аннотацию `@Nullable`.

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +        return new ArrayList<>(stepMap.values());
1. `Collections.unmodifiableList`
2. У тебя Map не обеспечивает порядок, хотя поряд у Шагов имеет значение. посмотри в `WebDataGrid` на поле `columnsOrder`.

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +        tourShowListeners.remove(listener);
NPE, если я попробую удалить слушатель раньше чем его добавили.

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +            tour.removeShowListener(this.tourShowListener);
`tourShowListener` тоже надо обнулять, зачем занимать лишнюю память

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +    public Action startAction() {
Что это и зачем?

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/StepEvent.java
> +        return null;
Почему `null`?

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/StepEvent.java
> +        return null;
Почему `null`?

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +    Tour getTour();
Положи рядом с сеттером

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +    List<WebStepButton> getButtons();
В интерфейсе не должны фигурировать конкретные имплементации.

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +    void addCancelListener(StepCancelListener listener);
Рекомендации аналогичные Tour

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +public interface Step {
Сгруппируй методы по логичскому предназначению. Методы относящие к кнопкам и размеру раскиданы по интерфейсу.

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +public class WebStep implements Step, Sizeable {
Что это за номер такой, взять и реализовать `com.vaadin.server.Sizeable`? А что будут делать люди, которые с интерфейсом работают? Посмотри на методы установки размера в компонентах и как этот самый размер ковертируется и добавь в Step нужыне методы.

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +        WebTour webTour = (WebTour) tour;
Аналогичный комментарий, что и в Tour

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +        WebStepButton webStepButton = (WebStepButton) button;
Аналогичный комментарий, что и в Tour

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +            step.removeCancelListener(this.stepCancelListener);
Аналогичный комментарий, что и в Tour

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +    protected HashMap<org.vaadin.addons.producttour.button.StepButton, WebStepButton> buttonMap = new HashMap<>();
Аналогичный комментарий, что и в Tour. Иметь такую Мапу жирно

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +        step = new org.vaadin.addons.producttour.step.Step(id, abstractComponent, WebWrapperUtils.toVaadinStepAnchor(anchor));
Создание в метод

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +        step.setSizeFull();
Настройки компонента в метод `initComponent()`

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/StepButton.java
> +            public int getClientX() {
Не надо вот этого всего, просто возвращай `MouseEventDetails`, там ест ьвсе что нужно и даже больше.

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/StepButton.java
> +    void addStepButtonClickListener(StepButtonClickListener stepButtonClickListener);
Опять же забыаешь логически сортировать методы. Положи эти методы рядом с интерфейсом... от которого надо избавиться в соответствии с рекомендациями в Tour.

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/StepButton.java
> +            private final Component.MouseEventDetails details;
а чем MouseEventDetails так отличается от source, что аж `private final`, а он просто `protected`?

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/StepButton.java
> +        abstract class ClickEvent implements TourProvider {
Мы эвенты наследуем от `java.util.EventObject`, который обеспечивает наличие поля source. Примеры в платформе сможешь найти.

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStepButton.java
> +                        return getStep().getTour();
*Стикер с офигевшим лицом Харламова*

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStepButton.java
> +    protected org.vaadin.addons.producttour.button.StepButtonClickListener stepButtonClickListener;
Комментарии аналогичные другим классам

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebWrapperUtils.java
> +public class WebWrapperUtils {
У нас нет смыла в утильном классе, т.к. никто кроме наших классов это использовать не будет. Если бы скажем ContentMode использовался и в Туре и в Шаге и т.д., тогда да. Методы в соответствующие классы.

2018-08-01 11:57 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTourActions.java
> +        TourActions.back(() -> ((WebTour) provider.getTour()).getTour());
Нет смысла так прокидывать. Простосделай такую ще реализацию. Но вообще мне этот класс не нравится. Он привязан к Web, и люди, у которых экран в GUI, не будут иметь доступ к дефолтным действиям. Подумай как переделать. 

Еще у тебя нету стандартных действий для Step.

2018-08-01 12:51 UTC, SemenSofronov commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +    public Action startAction() {
Сделал, чтобы каждый раз не надо было так писать для запуска тура

2018-08-03 09:38 UTC, glebfox requested changes

2018-08-03 09:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +    <X> X getStep();
Ты скомбинировал `unwrap` и `getComponent` в один не самый удачный метод. Для информации, посмотри на `getCompoennt` компонентов в платформе, но в твоих интерфейсах давай заведем именно аналог `unwrap`.

2018-08-03 09:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +        public StepEvent(Object source) {
Твой `Event` совершенно определенно принимает только `Step`. Так же переопредели `getSource()`, чтобы он возвращал `Step`.

2018-08-03 09:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Tour.java
> +    TourState getState();
Этот метод лишний, я имелл ввиду, что ты `etStepByIndex` пропустил.

2018-08-03 09:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/TourState.java
> +public interface TourState {
Удалить

2018-08-03 09:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStepButton.java
>          WebStep webStep = (WebStep) step;
Все еще `WebStep`

2018-08-03 09:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStepButton.java
> +        initWebStepButton(caption, style, consumer);
На сколько я помню, я рекомендовал вынести создание Vaadin компонента в отдельный метод, а его настройку, если таковая есть, в отдельный. Во всех классах ты создал метод `init`, в который по сути просто делегируешь то, что было раньше в конструкторе. 
В данном классе, тебе нужен только `createExtension` метод, а добавление слушателя так же останется в конструкторе.

2018-08-03 09:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStepButton.java
> +    protected List<Consumer<ClickEvent>> consumerList = null;
Переименовывать поле не было необходимости, т.к. это по прежнему слушатели, просто без собственного интерфейса. Верни как было.

2018-08-03 09:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +        initWebStep(id, attachTo, anchor);
Смешались в кучу кони, люди... еще раз, отдельный метод создания Ваадиновского компонента, отдельный метод настройки Ваадиновского компонента, остальное в конструкторе.

2018-08-03 09:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> -    @Override
И куда они пропали? Помнится я писал, что ты должен в твой интерфейс перенести соответствующие методы, посмотрев в платформе какие мы используем методы для задания размеров.

2018-08-03 09:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +    protected void initWebTour() {
createExtension

2018-08-03 09:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
>      protected org.vaadin.addons.producttour.tour.Tour tour;
Во всех твоих реализациях, оборачиваемый Ваадиновский компонент имеет свое уникальное имя, которое никак не обозначает, что это именно Ваадиновский компонент. Если в Туре это не так заметно, то в других классах, где рядом есть `tour` и `step` и один из них ваадиновский, а другой наш, становится трудно понять с чем имеешь время. Я думаю, что по аналогии, как сделано в платформе, будет хорошо, елси во всех классах, оборачиваемый ваадиноский компонент будет иметь одинаковое имя, например `extension`, т.к. они все расширения по сути.

2018-08-03 09:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +        if (tourShowListeners.contains(listener)) {
Это не спасет тебя от NPE, про который я тебе писал. Более того, такой if является лишним, о чем тебе должна была сказать IDEA.

2018-08-03 09:41 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +        return stepMap.get(step);
На половину комментария ты забил

2018-08-03 09:43 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +    public Action startAction() {
Создай отдельно живущий `TourAction`, который будет принимать Тур и делать все что надо, но нельзя хранить такое в компоненте

2018-08-03 09:44 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +public class WebStep implements Step, Sizeable {
ТОже забил на половину комментария

2018-08-07 12:10 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
>      protected org.vaadin.addons.producttour.tour.Tour tour;
Я ведь даже написал конкретное имя поля - `extension`. Посмотри на кубинские компоненты, везде используется `component` как основной оборачиваемый компонент.

2018-08-07 12:15 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +    protected void initWebTour() {
Опять поигнорировал мой коммент

2018-08-07 12:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStepButton.java
> +    protected Step stepExtended;
А зачем ты поле переименовал?

2018-08-07 12:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +            for (Consumer<ShowEvent> showEventConsumer : tourShowListeners) {
А зачем это появилось? От NPE ты избавился, молодец, но зачем бегать руками по массиву и искать совпадения? Прочитай внимательно как работает метод `remove`.

2018-08-07 12:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/TourStartAction.java
> +public class TourStartAction extends AbstractAction {
1. `extends BaseAction`
2. Посмотри на стандарные действия типа CreateAction, EditAction etc. Я хочу, чтобы твое действие тоже было бино, тогда его легко будет переопределить в системе.

2018-08-07 12:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +    void setTourExtended(Tour tourExtended);
Зачем ты их переименовал?

2018-08-07 12:38 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +        initWebStep(id, attachTo, anchor);
Еще раз. Метод создания компонента/расширения ТОЛЬКО создает и возвращает, например:
```
public Constructor() {
   conponent = createComponent();
   initComponent(conponent);
}

protected SomeComponent createComponent() {
   return new SomeComponent();
}

protected void initComponent(SomeComponent component) {
  // aply some setting etc.
}
```

2018-08-07 12:42 UTC, glebfox requested changes

2018-08-07 12:42 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +        createExtension(null, attachTo, anchor);
Почему все конструкторы каждый раз делают одно и тоже? Без крайней необходимости конструкторы вызывают друг друга

2018-08-07 12:42 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +            for (Consumer<CancelEvent> cancelEventConsumer : stepCancelListeners) {
Аналогичный комментарий, это все лишнее

2018-08-07 12:42 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +    public <X> X getStep(Class<X> internalClass) {
Опять же, зачем уникальное имя? ну назови как в компонентах `unwrap`. Тем более, что `get` тут не уместен.

2018-08-08 08:34 UTC, glebfox requested changes

2018-08-08 08:34 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/TourStartAction.java
> +    public static final String ACTION_ID = "start";
Слишком общее имя. `tourStart`

2018-08-08 08:34 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStepButton.java
> +        initExtension(style, consumer);
ну мы же с тобой обсуждали, и я даже пример написал, что в `init` передается сам компонент, который будет проиницыализирован. И в этом метоже проставляются значения в сам ваадиновский компнент. Почему добавление слушателя к WebStepButton происходит в этом методе?

2018-08-08 08:34 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStepButton.java
>      public WebStepButton(String caption, String style, Consumer<ClickEvent> consumer) {
Почему конструктор принимает больше параметров чем требуется для минимульной инициализации? Стиль, если требуется можно потом поставить. И что такое `consumer`? Из названия входного поля мне не понятно для чего оно.

2018-08-08 08:34 UTC, glebfox commented on modules/web/src/ui-component.xsd
> +    <xs:element name="tour">
Если мы не собираемя описывать компонент в XML, то зачем нам нужен этот элемент?

2018-08-08 08:34 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +        initExtension(attachTo, anchor);
Аналогичное замечание

2018-08-08 08:34 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +        attachedTo = attachTo;
`attachedTo` поле `WebStep`, значит этот метод не место, чтобы его инициализировать.

2018-08-08 08:34 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
>      public WebStep(String id, com.haulmont.cuba.gui.components.Component attachTo, StepAnchor anchor) {
Оставь один конструктор с минимальным количесвом параметров, необходимых для инициализации компонента. Все остальные удали.

2018-08-08 08:35 UTC, glebfox requested changes

2018-08-08 08:35 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +        if (id == null) {
Если id не может быть null, сделай проверку и кидай исключение:
```
Preconditions.checkNotNullArgument(id);
```

2018-08-08 08:38 UTC, SemenSofronov commented on modules/web/src/ui-component.xsd
> +    <xs:element name="tour">
Я думал, что мы собирались, но я этим ещё не занимался.

2018-08-08 09:22 UTC, glebfox commented on modules/web/src/ui-component.xsd
> +    <xs:element name="tour">
Попробуй определить возможность, потому что что писать в XML мы с тобой уже определили, все упирается в тот факт, что это extension, а не компонент и не понятно будут ли Лоадеры работать, т.к. есть вероятность, что они ждут только Component, так же как и фабрика.

2018-08-08 10:07 UTC, glebfox requested changes

2018-08-08 10:07 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStep.java
> +        Preconditions.checkNotNullArgument(id);
Это нужно проверять в конструкторе, если кто то будет переопределять твой метод, ему нужно будет знать, что необходима такая проверка, а это не правильно. Тем более id, который передается, является входным параметром конструктора, а значит толжен в нем и проверяться, иначе выброшенное исключение будет не там где реально произошла ошибка.

2018-08-08 10:07 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStepButton.java
>      public void addStepButtonClickListener(Consumer<ClickEvent> consumer) {
Я уже неоднократно писал, что `consumer` не сочетается с тем, чем по факту является входной параметр. Переименуй в `listener`.

P.S. Везде проверь как у тебя называются поля и входные параметры

2018-08-08 13:43 UTC, glebfox requested changes
Теперь создай WebAbstractExtension и вынеси в него общую логику. В качестве вдохновения используй WebAbstractComponent из платформы

2018-08-14 14:42 UTC, glebfox requested changes

2018-08-14 14:42 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +        ArrayList steps = new Gson().fromJson(json, ArrayList.class);
1. Форматирование хромает (пчоему бы не взять лоадеры за основу структурирования подобного кода).
2. Сделай бином, синглтон убери, бин сам по себе бидет синглтоном 
3. GSon сделай статическим
4. Не все поля парсишь.
5. Парсеру нужен будет юнит тест

2018-08-14 14:42 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +        switch (contentMode) {
Посмотри в лоадерах, как парсястся перечисления

2018-08-14 14:42 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +            case "next": {
1. Посмотри на `com.haulmont.cuba.gui.components.actions.ListActionType` и подумай, как ты можешь отрефакторить свой `TourActions` и `StepActions`
2. Когда посмотришь как в лоадерах парсятся перечисления примени опыт на Экшены

2018-08-16 13:57 UTC, SemenSofronov commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +        ArrayList steps = new Gson().fromJson(json, ArrayList.class);
Я не паршу сейчас только то, к чему Step прикрепляется и с какой стороны, потому что в json компонент не укажешь, а без компонента и Anchor не имеет значения. Если нужно будет это задать, то в программе можно получить у тура шаги и прикрепить их к чему нужно.

2018-08-17 15:11 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +    protected static final Map<String, Step.ContentMode> contentModeMap =
Зачем это? А если в enum ты еще значений добавишь? Каждый раз бегать и править все такие места? Сделай метод `fromId`, типа такого:
```
@Nullable
public static DatePeriod fromId(String id) {
    for (DatePeriod period : values()) {
        if (period.getId().equals(id)) {
            return period;
        }
    }
    return null;
}
```

2018-08-17 15:14 UTC, glebfox requested changes

2018-08-17 15:14 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +    public String getModal(LinkedTreeMap stepMap) {
Почему они все публичные?

2018-08-17 15:14 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +            ImmutableMap.<String, Step.ContentMode>builder()
Зачем это? А если в enum ты еще значений добавишь? Каждый раз бегать и править все такие места? Сделай метод `fromId`, типа такого:
```
@Nullable
public static DatePeriod fromId(String id) {
    for (DatePeriod period : values()) {
        if (period.getId().equals(id)) {
            return period;
        }
    }
    return null;
}
```

2018-08-17 15:17 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +        ArrayList steps = new Gson().fromJson(json, ArrayList.class);
Что значит не имеет значения? Я хочу Полностью описать кофигурацию Тура в JSON, распрсить ее твоим Парсером и заэкстендить экран и все. Получается твой парсет только частично что то делает а дальше нужно руками писать код, чтобы пробежаться по шагам и как то их донастроить. Так дело не пойдет

2018-08-17 15:28 UTC, glebfox requested changes

2018-08-17 15:28 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +    protected ArrayList steps;
Зачем?

2018-08-17 15:28 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
>          this.messages = messages;
Заинжекть сам

2018-08-17 15:28 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
>      protected static Gson gson = new Gson();
Короче, переделывай Парсер. 

1. Куча ненужных публичных полей. 
2. Неправильно работаешь с перечилениями и парсишь их
3. Структура кода неправильная, я уже много раз писал, что не нужно объявлять кучу переменных а потом только через несколько строк их использовать.
4. Снова забил на мои комментарии, хотя я писал посмотреть на структуру лоадеров компонентов и сделать по такому же принципу.
5. Названия методов не соответствуют их поведению. например, `setSteps` парсит json, а не просто устанавливает значение. 
6. Не загружаешь все настройки

2018-08-18 07:29 UTC, SemenSofronov commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +    public String getModal(LinkedTreeMap stepMap) {
Гетеры и сетеры же обычно публичные, я их использую в тестах

2018-08-18 07:40 UTC, SemenSofronov commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +    protected ArrayList steps;
Чтобы в тесте не нужно было создавать экземпляр Тура, так как он не может расширить ничего. Я просто там паршу json и проверяю как считываются данные без проставления их полям тура, или шагов, или кнопкам.

2018-08-18 10:00 UTC, SemenSofronov commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
>      protected static Gson gson = new Gson();
4. Я смотрел на лоадеры, они загружают каждый компонент отдельно, я вроде так и попытался сделать. Как конкретно оно должно быть?

2018-08-23 12:01 UTC, glebfox requested changes

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStepButton.java
> +     * DO NOT USE!
Если этот метод для внутреннего пользования, то его не нжно было прокидывать к нам. Разберись нужен ли он нам, можем ли мы без него обойтись и убери, если возможно. Нам не нужно повторять косяки архитектуры ваадин аддона

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStepButton.java
> +     * @see Component#removeStyleName(String)
1. Почему доки в реализации, а не в интерфейсе? 
2. Не зачем повторять халтуру автора аддона. Пиши нормальные JavaDoc.

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/StepButton.java
> +    List<Consumer<ClickEvent>> getClickListeners();
Зачем?

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebTour.java
> +        public CubaTour(AbstractClientConnector target) {
Напиши подробный коммент, нафига мы такое нагородили. По коду не понятно, что это сделано для того, чтобы эксендить не весь UI, а компонент по нашему выбору и т.д

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/TourStartAction.java
> +    protected TourStartAction(String id, @Nullable String shortcut, Tour tour, String userSetting) {
Зачем этот констурктор?

2018-08-23 12:01 UTC, glebfox commented on modules/web/test/com/haulmont/scenario/mytour
>  [
переименуй файл, что то типа `tour.json`

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +        messages = AppBeans.get(Messages.class);
Это ж бин, что мешает заинжектить?

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +        extension = extensionFor;
Тебе нужно разобраться со `Scope` бинов. В данном случае твой бин как singleton, а ты так просто меняешь в нем филды. Что будет, если несколько пользователей одновременно запустят твой парсер для разных экранов?

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +            LinkedTreeMap stepMap = (LinkedTreeMap) step;
Есть какое то обоснование почему переменная имеет конкретный тип, а не общий интерфейс? Аналогично для входного параметра методов.

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +        id = UUID.randomUUID().toString();
`UuidSource` для таких случаев, но вообще Юзер должен задать id. Кидай исключения, если id нету

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +        return new WebStep(id);
Может создавать ты будешь один раз, а перед этим переменная `id` полуит значение или тз файла или рандомное?

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +        Step webStep = createStepWithId(stepMap);
почему `webStep`?

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +        return new WebStepButton("Test");
Ничего себе нормер. Проверь, что будет если заголовок будет пустая строка, если ничего хорошего не выйдет, то кидай исключение, типа заголовок обязательное поле.

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +            if (cubaComponent != null) {
А если юзер вместо `id` компонента какую то фигню напишет? Я думаю, что в данном случае надо кидать исключение, т.к. если ользователь пытается привязать к компоненту, он жолжен уззнать, что конфигурация неправильная.

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +                webStep.setAnchor(Step.StepAnchor.RIGHT);
Не должен лоадер устанавливать значения по умолчанию, если такие нунжы, но они должны быть прописаны в копоненте, иначе будет отличаться тур, загруженный лоадером и созданный программно пользователем, в лучае если не будут указаны одни и те же параметры.

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +                webStep.setTitleContentMode(Step.ContentMode.TEXT);
Аналогично

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +    protected void loadClickListener(LinkedTreeMap buttonMap, StepButton stepButton) {
По факту, Ты загружаешь одино из дефолтных действий. Имя метода фрустрирует.

2018-08-23 12:01 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
>          if (split.length == 2) {
И снова пользователь может понаписать полной фигни и даже не узнает об этом.

2018-08-23 12:01 UTC, glebfox commented on modules/web/test/com/haulmont/scenario/TourParserTest.java
> +        @Override
Тест не компилится

2018-08-23 12:01 UTC, glebfox commented on modules/web/test/com/haulmont/scenario/TourParserTest.java
> +                                                                            Component extensionFor) {
И вообще, раз мы в платформе перешли на `Spock`, почему бы тебе и тут на нем не делать тесты?

2018-08-23 12:08 UTC, SemenSofronov commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +        id = UUID.randomUUID().toString();
В аддоне, если не указан id  в конструкторе, то он генерируется таким способом и передаётся в следующий конструктор. Поэтому я так же сделал, чтобы генерировался, если не указан. id же указывают, если имеют целью к ним обратиться, а если никому это не требуется, то и не важно какой id задан, но он обязателен.

2018-08-23 12:12 UTC, SemenSofronov commented on modules/web/test/com/haulmont/scenario/TourParserTest.java
> +                                                                            Component extensionFor) {
А как его правильно подключить? А то я начал сначала в груви писать, но тут нету что ли подключенной библиотеки?

2018-08-23 12:16 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +        id = UUID.randomUUID().toString();
Если в аддоне есть конструктор без `id`, почему нас тогда id строго обязателен? У него вон и метод `setId` есть оказывается.

2018-08-23 12:25 UTC, glebfox commented on modules/web/test/com/haulmont/scenario/TourParserTest.java
> +                                                                            Component extensionFor) {
Подключи Spock рядом c `junit` , groovy и так работает 

```
testCompile('org.spockframework:spock-core:1.1-groovy-2.4-rc-2') {
    exclude(group: 'org.codehaus.groovy', module: 'groovy-all')
}
```

2018-08-23 12:30 UTC, SemenSofronov commented on modules/web/src/com/company/scenarioaddon/web/gui/components/TourStartAction.java
> +    protected TourStartAction(String id, @Nullable String shortcut, Tour tour, String userSetting) {
Я добавил возможность при создании действия запуска тура указать название UserSetting, которое будет внутри отслеживаться для вызова тура только при первом вызове действия.

2018-08-24 07:17 UTC, SemenSofronov commented on modules/web/src/com/company/scenarioaddon/web/gui/components/StepButton.java
> +    List<Consumer<ClickEvent>> getClickListeners();
В общем, я это добавил, чтобы в тесте можно было хоть как-то проверить, что действие для кнопки загрузилось. Если без этого, я не могу придумать, как проверять, потому что тогда только 2 действия доступны, удалить и добавить, которые ничего не возвращают и не выбрасывают исключений. Можно это оставить или как проверять, что на кнопку навешен слушатель?

2018-08-24 07:26 UTC, SemenSofronov commented on modules/web/src/com/company/scenarioaddon/web/gui/components/WebStepButton.java
> +     * DO NOT USE!
Это необходимый метод для связи кнопки и шага, подобный используется для связи шага и тура. Добавляя шаг к туру, мы не просто добавляем шаг в массив шагов тура, но также проставляем шагу тур, которому он принадлежит. И в этом случае так же. Эти методы необходимы, так как после проставления этих зависимостей, с помощью методов `getTour()`, `getStep()`, `getStepButton()` реализуется механика провайдеров, передающая информацию для эвентов.

2018-08-24 12:04 UTC, SemenSofronov commented on modules/web/test/com/haulmont/scenario/TourParserTest.java
> +                                                                            Component extensionFor) {
В CubaClientTestCase очень много содержится для инфраструктуры теста и без его наследования не знаю, как получить в этом тесте Messages. Обязательно переделывать тест на груви?

2018-08-27 10:47 UTC, glebfox requested changes

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +     * @return <code>true</code> if the step is currently visible, <code>false</code> else
Поменяй `else` на `otherwise`

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +     * Set the component the step should be attached to.
**should** означет _должен_, но не _обязан_, если я везде верно путаю, то вероятность 50%. В данном случае шаг **будет** добавлен к компоненту.

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +     * Set the cancellable state of the step.
**Sets**

Смысл в следующем, ты как бы пишешь, что _Метод устанавливает ...._, т.е. **Method sets** (т.к. это 3е лицо). Слово _метод_ опускается, но 3е лицо остается.

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +     * @return the buttons of the step inside an unmodifiable container
Если бы я не знал, что бы оборачиваешь список кнопок в `Collections.unmodifiableList`, я бы нифига не понял. В данном случае **inside** и **container** неуместные слова. 
`the unmodifiable list of step buttons`

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +     * @param listener the listener to be removed.
Точка для Param и Remove не ставится.

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/TourStartAction.java
> +        hasSetting = true;
Я вот не пойму, мы воде обговорили все на тему этой настройки. Почему у тебя просто метод который включает и все? А если я выключить захочу? Разве в Table, который я тебе советовал взять за пример, метод `setSettingsEnabled` так работает? Как сочетается имя метода и его поведение?

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/TourStartAction.java
> +            String settingName = component.getId() + ":" + ACTION_ID;
вынеси формирование Id в метод, чтобы можно было его переопределить, на случай, если конечный юзер захочет свои Id пилить.

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/TourStartAction.java
> +            String startAction = userSettingService.loadSetting(ClientType.WEB, settingName);
Ты уверен, что имя переменной сочетается с ее назначением?

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/TourStartAction.java
> +            return;
Может ты просто добавишь `else` для `if`? Код читабельнее будет. return хорош в начале метода, когда ты что то проверяешь и в случае чего завершаешь метод, чтобы не оборачивать все в большой if. Тут у тебя нет никакой необходимости в return

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
>   * Parser for {@link WebTour} objects
parser **of**

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +    protected Window extension;
`extension` это то, что расширяет, а не то, что расширяют

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +        Tour tour = new WebTour(extension);
Ты бы лучше создание Тура в метод вынес

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +    protected void loadStep(Map stepMap, Tour tour) {
ты же говорил, что у тебя Map строки содержит? Почему до сих пор объект нетипизированный?

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +                Map<String, String> buttonMap = (Map<String, String>) button;
у тебя тут warning. Если точно все работает, то затуши его через коммент

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +                throw new IllegalArgumentException("Action value is wrong!");
не используй слово wrong. В таких случаях надо использовать **incorrect**. Но в данном случае лучше более адекватное исключчение: Не смог распарсить, или смог, но экшена с таким id нету.

2018-08-27 10:47 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +                throw new IllegalArgumentException("AttachTo id is wrong!");
Фу фу фу, такие сообщения в исключениях

2018-08-27 10:47 UTC, glebfox commented on modules/web/test/com/haulmont/scenario/TourParserTest.java
>          textField1.setId("button1");
Тебя не смущает, что ты создаешь TextField, в id у него button?

2018-08-27 10:47 UTC, glebfox commented on modules/web/test/com/haulmont/scenario/TourParserTest.java
> +        } catch (IllegalArgumentException e) {
Если предполагается, что будет исключение и нет какого то сложного кейса, то их тестят по другому.

2018-08-27 10:47 UTC, glebfox commented on modules/web/test/com/haulmont/scenario/TourParserTest.java
> +        String file = Objects.requireNonNull(resources.getResourceAsString("com/haulmont/scenario/json_data/incorrectAttachTo.json"));
У тебя какая то необоснованная любовь к этому методу `Objects.requireNonNull`. Ты и так знаешь, что файл такой есть, т.к. он лежит у тебя захардкоженный. Если его кто то удалит или переименует, то тест и так упадет.

2018-08-27 11:44 UTC, SemenSofronov commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +    protected void loadStep(Map stepMap, Tour tour) {
Там stepMap ещё содержит массив кнопок, поэтому я его просто Object оставил, а вот buttonMap типизировал

2018-08-27 11:51 UTC, SemenSofronov commented on modules/web/test/com/haulmont/scenario/TourParserTest.java
> +        String file = Objects.requireNonNull(resources.getResourceAsString("com/haulmont/scenario/json_data/incorrectAttachTo.json"));
Это всё подсказки студии, в нескольких местах так, мне тоже делать SupressWarning?

2018-08-27 12:00 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +    protected void loadStep(Map stepMap, Tour tour) {
`Map<String, Object` тогда уж

2018-08-28 05:58 UTC, SemenSofronov commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +     * @param listener the listener to be removed.
Я вот для примера открыл интерфейс `Component`, там по-разному сделано. Не помню, что я именно брал в пример, но сейчас я старался сделать, чтобы после описания стояла точка, а в параметрах и return не стояла, тогда тут я не заметил, теперь исправил.

2018-08-28 06:00 UTC, SemenSofronov commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +     * Set the cancellable state of the step.
Я переделал везде на 3 лицо, но в интерфейсе `Component` сделано по-разному.

2018-08-28 07:05 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
> +     * @param listener the listener to be removed.
А если ты откроешь аннотации к коду, то увидишь, что такие коментарии были написанны очень давно.

2018-08-28 07:14 UTC, glebfox requested changes

2018-08-28 07:14 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/Step.java
>       * @param internalClass class of underlying component implementation based on Vaadin
Давай уберем `based on Vaadin`. Такие подробноти лишние, т.к. теоретически никто не запрещает сделать другую реализацию данного интерфейса.

2018-08-28 07:14 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> + * Parser of {@link WebTour} objects
Просто `Tour`. WebTour всего лишь частная реализация интерфейса.

2018-08-28 07:14 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +                throw new IllegalArgumentException("TextContentMode value not found!");
Ты поменял шило на мыло. Если я что то укажу, но это не будет являться ID перечисления, то твое сообщение будет фрустрировать разработчика. Если прям хочется что то общее, то напиши, что распарсить не смог.

2018-08-28 07:14 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/utils/TourParser.java
> +                throw new IllegalArgumentException("TextContentMode value not found!");
Давай будем бросать `GuiDevelopmentException` как это делается в лоадерах платформы.

2018-08-28 07:14 UTC, glebfox commented on modules/web/src/com/company/scenarioaddon/web/gui/components/TourStartAction.java
> +            String startAction = userSettingService.loadSetting(ClientType.WEB, settingName);
В очередной раз ты забил на мои комментарии

2018-08-28 08:15 UTC, glebfox requested changes

2018-08-28 08:15 UTC, glebfox commented on modules/web/test/com/haulmont/scenario/TourParserTest.java
> +    @Test(expected = GuiDevelopmentException.class)
У тебя там `public ExpectedException exception = ExpectedException.none();` зачем то объявлено

2018-08-28 08:17 UTC, SemenSofronov commented on modules/web/test/com/haulmont/scenario/TourParserTest.java
> +    @Test(expected = GuiDevelopmentException.class)
Это я не уследил, добавил, когда смотрел методы обработки исключений

2020-02-12 13:26 UTC, merged